### ISSUE TITLE
Option to not panic if envvar is not set

### ISSUE THREAD

**Issue by Oppodelldog** [Oppodelldog/droxy#43]
Currently if a environment variable is defined to be mapped in toml the command panics id the environment variable is not set at runtime.

This makes sense for debugging the droxy command during developing it, but the reuse of common configuration is more complicated.

So there should be a flag to prevent command from panicing if a environment variable cannot be resolved.

Sample:
```toml
[[command]]
    name="php7"
    image="php7-dbg"
    envvars=[
        "XDEBUG_CONFIG=${XDEBUG_CONFIG}"
    ]

```
if XDEBUG_CONFIG is not set at runtime, thge program panics.
